services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dolla
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aoc2023d2
    ports:
      - 9001:5432
    volumes:
      - aoc2023d2:/var/lib/postgresql/data
      - ./postgres:/postgres

volumes:
  aoc2023d2:
